title:              Kurt Eulau
email:              kurteulaudata@gmail.com
description:        Portfolio
author:             Kurt Eulau
baseurl:            ""
url:                "https://kurteulau.github.io"

# Social Profiles
twitter_username:   
github_username:    kurteulau
facebook_username:  
instagram_username:  
linkedin_username: kurt-eulau

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
